package pl.preclaw.florafocus.data.local.entities

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import androidx.room.TypeConverters
import pl.preclaw.florafocus.data.local.database.Converters

/**
 * Task entity for garden activities
 * 
 * Represents both user-created and auto-generated tasks
 * Can be linked to specific plants or be general garden tasks
 */
@Entity(
    tableName = "tasks",
    foreignKeys = [
        ForeignKey(
            entity = UserPlantEntity::class,
            parentColumns = ["id"],
            childColumns = ["plantId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [
        Index("userId"),
        Index("plantId"),
        Index("dueDate"),
        Index("isCompleted"),
        Index("locationId")
    ]
)
@TypeConverters(Converters::class)
data class TaskEntity(
    @PrimaryKey
    val id: String,
    
    val userId: String,
    val plantId: String?, // Optional - link to specific plant
    
    // Task details
    val title: String,
    val description: String?,
    
    // Scheduling
    val dueDate: Long,
    val dueDateFlexible: Boolean = false, // Can system reschedule based on weather?
    val originalDueDate: Long? = null, // Original date before auto-rescheduling
    
    val completedDate: Long?,
    val isCompleted: Boolean = false,
    val completionNotes: String? = null,
    
    // Recurrence
    val isRecurring: Boolean = false,
    val recurrencePattern: RecurrencePattern? = null,
    val recurrenceIntervalDays: Int? = null, // For custom patterns
    val nextOccurrenceDate: Long? = null, // When this task should repeat
    
    // Priority & categorization
    val priority: TaskPriority = TaskPriority.MEDIUM,
    val taskType: TaskType,
    
    // Auto-generation metadata
    val autoGenerated: Boolean = false,
    val generatedByPhaseId: String?, // Which growth phase triggered this task
    val generatedByTemplateId: String?, // Recurring template that generated this
    val weatherDependent: Boolean = false,
    
    // Location for grouping
    val locationId: String?, // bedId or areaId for task grouping
    val locationName: String?, // Cached location name
    val cellRow: Int? = null, // Specific cell if applicable
    val cellColumn: Int? = null,
    
    // Assignment (for multi-user in future)
    val assignedTo: String? = null,
    val assignedBy: String? = null,
    
    // Reminders
    val reminderEnabled: Boolean = true,
    val reminderTimeBefore: Int? = null, // Hours before due date
    val reminderSent: Boolean = false,
    val reminderSentDate: Long? = null,
    
    // Progress tracking
    val estimatedDurationMinutes: Int? = null,
    val actualDurationMinutes: Int? = null,
    val difficultyRating: Int? = null, // 1-5 scale after completion
    
    // Resources needed
    val toolsNeeded: List<String> = emptyList(),
    val materialsNeeded: List<String> = emptyList(),
    val costEstimate: Float? = null,
    val actualCost: Float? = null,
    
    // Results tracking
    val successRating: Int? = null, // 1-5 scale
    val resultNotes: String? = null,
    val beforePhotoUrls: List<String> = emptyList(),
    val afterPhotoUrls: List<String> = emptyList(),
    
    // Weather conditions when completed
    val weatherConditions: String? = null,
    val temperature: Float? = null,
    
    // Dependencies
    val dependsOnTaskIds: List<String> = emptyList(), // Tasks that must be completed first
    val blockedByWeather: Boolean = false,
    val minimumTemperature: Float? = null,
    val maximumTemperature: Float? = null,
    
    // Status flags
    val isArchived: Boolean = false,
    val isCancelled: Boolean = false,
    val cancellationReason: String? = null,
    
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)

/**
 * Template for recurring tasks
 * 
 * Used to generate repeating tasks automatically
 */
@Entity(
    tableName = "recurring_task_templates",
    indices = [
        Index("userId"),
        Index("isActive")
    ]
)
@TypeConverters(Converters::class)
data class RecurringTaskTemplateEntity(
    @PrimaryKey
    val id: String,
    
    val userId: String,
    
    // Template details
    val name: String,
    val description: String?,
    val taskType: TaskType,
    val priority: TaskPriority = TaskPriority.MEDIUM,
    
    // Recurrence settings
    val recurrencePattern: RecurrencePattern,
    val intervalDays: Int, // For custom patterns
    val startDate: Long,
    val endDate: Long? = null, // Optional end date
    
    // Season/time restrictions
    val activeSeasons: List<Season> = emptyList(), // Empty = all seasons
    val minimumTemperature: Float? = null,
    val maximumTemperature: Float? = null,
    val skipInWeather: List<String> = emptyList(), // "rain", "snow", "frost"
    
    // Location targeting
    val appliesToAllGardens: Boolean = true,
    val specificGardenIds: List<String> = emptyList(),
    val specificAreaIds: List<String> = emptyList(),
    val specificBedIds: List<String> = emptyList(),
    
    // Auto-scheduling
    val flexibleScheduling: Boolean = false,
    val reminderHoursBefore: Int = 24,
    val estimatedDurationMinutes: Int? = null,
    
    // Resources
    val defaultToolsNeeded: List<String> = emptyList(),
    val defaultMaterialsNeeded: List<String> = emptyList(),
    
    // Status
    val isActive: Boolean = true,
    val lastGeneratedDate: Long? = null,
    val nextGenerationDate: Long? = null,
    
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)
